name: Deploy to Vultr (SSH)

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (for version metadata only)
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            set -e
            if ! command -v git >/dev/null 2>&1; then
              apt-get update -y && apt-get install -y git
            fi
            if ! command -v node >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
              apt-get install -y nodejs
              npm i -g pm2
            fi

            APP_DIR="${{ secrets.APP_DIR }}"
            REPO_URL="${{ secrets.REPO_URL }}"

            mkdir -p "$APP_DIR"

            if [ -d "$APP_DIR/.git" ]; then
              cd "$APP_DIR"
              git fetch --all
              git reset --hard origin/$(git symbolic-ref --short HEAD || echo main)
            else
              git clone "$REPO_URL" "$APP_DIR"
              cd "$APP_DIR"
            fi

            npm ci --omit=dev
            pm2 delete naic2 || true
            pm2 start server.js --name naic2
            pm2 save